const CONST={M2:0.32,S2:0.15,N2:0.06,K1:0.09,O1:0.06};
const BANDS=[[4,6],[6,8],[8,10],[10,12],[12,14],[14,16],[16,22]];
function tideH(ms,lat){const t=ms/1000,lag=(4.175-lat)*6*60,tt=t+lag,rad=x=>x*Math.PI/180;const h=CONST.M2*Math.cos(rad(28.9841*(tt/3600)+18))+CONST.S2*Math.cos(rad(30*(tt/3600)))+CONST.N2*Math.cos(rad(28.4397*(tt/3600)+12))+CONST.K1*Math.cos(rad(15.0411*(tt/3600)+90))+CONST.O1*Math.cos(rad(13.943*(tt/3600)+70));return Math.round(h*100)/100;}
function band(h){return h>0.22?"high":h<-0.18?"low":"mid"}
function card(d){const x=["N","NNE","NE","ENE","E","ESE","SE","SSE","S","SSW","SW","WSW","W","WNW","NW","NNW"];return x[Math.round((((d%360)+360)%360)/22.5)%16]}
function ang(a,b){const d=Math.abs(a-b)%360;return d>180?360-d:d}
function inArc(d,s,e){d=((d%360)+360)%360;s=((s%360)+360)%360;e=((e%360)+360)%360;return s<=e?d>=s&&d<=e:d>=s||d<=e}
function mid(s,e){s=((s%360)+360)%360;e=((e%360)+360)%360;return s<=e?(s+e)/2:((s+e+360)/2)%360}
function power(h,t){return Math.round(0.49*h*h*t*10)/10}
function ft(m){return Math.round(m*3.28084*10)/10}
function hourMvt(ms){return +new Intl.DateTimeFormat("en-GB",{timeZone:MV,hour:"2-digit",hour12:false}).format(new Date(ms))}
function fmt(ms,opt){return new Intl.DateTimeFormat("en-GB",{timeZone:MV,...opt}).format(new Date(ms))}
function kmhToKn(v){return v/1.852}
function sourceOf(dir,T){if(T>=14&&inArc(dir,160,230))return "Southern Ocean groundswell · 3–5 day travel";if(T>=12&&inArc(dir,130,200))return "South Indian mid-latitudes";if(T>=10&&inArc(dir,200,260))return "Mascarene / SW monsoon fetch";if(T<9)return "Local windsea";return "Mixed Indian Ocean swell"}
function waitMin(Hs,Hfun,T){if(Hs<=0.15)return 99;const p=Math.exp(-Math.pow(Hfun/Math.max(Hs,0.2),2));return Math.min(90,Math.max(2,Math.round((T/Math.max(p,0.02))/60)))}
function currentRel(swellFrom,curTo){const travel=((swellFrom+180)%360+360)%360,a=ang(travel,curTo);if(a<50)return "follow";if(a>130)return "oppose";return "cross"}
function rate(spot,inp){const {h,dir,T,wkn,wdir,tb,hour,ckn,crel}=inp;let size=0;if(h<spot.min*0.45)size=0.1;else if(h<spot.min*0.75)size=1.1;else if(h<spot.min)size=2;else if(h<=spot.max*0.72)size=3.1;else if(h<=spot.max)size=2.6;else if(h<=spot.max*1.22)size=1.4;else size=0.4;let per=0.15;if(T>=16)per=2.5;else if(T>=13)per=2.15;else if(T>=11)per=1.7;else if(T>=9)per=1.1;else if(T>=7)per=0.55;const sd=ang(dir,mid(spot.sw[0],spot.sw[1]));let sws=inArc(dir,spot.sw[0],spot.sw[1])?Math.max(1.1,2.5-sd/50):Math.max(0,1-sd/70);const offM=mid(spot.off[0],spot.off[1]),onM=(offM+180)%360;let rel="cross",ws=0.8;if(wkn<5.5){rel="glassy";ws=2.05}else if(inArc(wdir,spot.off[0],spot.off[1])||ang(wdir,offM)<40){rel=ang(wdir,offM)<28?"offshore":"cross-off";ws=wkn<20?2.45:1.9}else if(ang(wdir,onM)<48){rel="onshore";ws=wkn<7?1.05:wkn<12?0.35:wkn<18?-0.4:-1.7}else{rel="cross";ws=wkn<11?1.35:wkn<17?0.55:0.05}const pw=power(h,T);let ps=pw>=8&&pw<=40?0.55:pw>40?0.2:0;let tide=0;if(spot.tide!=="all"&&tb){if(spot.tide==="mid-high")tide=tb==="low"?-0.7:tb==="mid"?0.25:0.35;if(spot.tide==="high")tide=tb==="high"?0.4:tb==="mid"?0.1:-0.55;if(spot.tide==="low")tide=tb==="low"?0.35:tb==="mid"?0.05:-0.25;}const chop=inp.ww>0?inp.ww/Math.max(h,0.2):0;let chs=0;if(chop>0.85&&T<9)chs=-1.1;else if(chop>0.55&&T<10)chs=-0.55;else if(chop<0.25&&T>=11)chs=0.25;let geo=0;if(T>=12&&inArc(dir,160,230)&&spot.lat<1.5)geo=0.28;if(T>=12&&inArc(dir,160,230)&&spot.lat>3.5)geo=-0.08;let raw=size+per+sws+ws+ps+tide+chs+geo;if(hour>=6&&hour<=11)raw+=0.28;else if(hour>=15&&hour<=17)raw+=0.08;else if(hour>=0&&hour<5)raw-=0.22;let flow="slack";if(ckn>=0.35){if(crel==="oppose"){flow="oppose";raw+=spot.chan?Math.min(0.55,0.18+ckn*0.22):Math.min(0.28,ckn*0.12);}else if(crel==="follow"){flow="follow";raw-=Math.min(0.55,0.12+ckn*0.18);}else{flow="cross";if(spot.chan)raw-=Math.min(0.35,ckn*0.12);}}if(h<0.32)raw=Math.min(raw,1.3);if(rel==="onshore"&&wkn>18&&h>0.45)raw=Math.min(raw,2.6);const score=Math.max(0,Math.min(10,Math.round(raw*10)/10));let label="Flat";if(rel==="onshore"&&wkn>18&&h>0.5)label="Blown";else if(h>spot.max*1.28)label="XL";else if(score>=8.6)label="Epic";else if(score>=7)label="Good";else if(score>=5.2)label="Fun";else if(score>=3.2)label="Small";const opt=rel==="offshore"||rel==="glassy"?1:rel==="cross-off"?0.72:rel==="cross"?0.4:0.12;return {score,label,rel,opt,flow};}
function tone(l){return l==="Epic"||l==="Good"?"good":l==="Fun"||l==="Small"?"ok":l==="Blown"||l==="XL"?"bad":"mut"}
const state={cells:{},wind:{},gfs:{},ecm:{},cur:{},wx:{},sel:(()=>{try{return localStorage.getItem("kandu:sel")||SPOTS[0].slug}catch(e){return SPOTS[0].slug}})(),q:"",atoll:""};
function ids(){return Object.keys(REG)}
function llFor(keys){return {lat:keys.map(k=>REG[k][0]).join(","),lon:keys.map(k=>REG[k][1]).join(",")}}
function wrapProxy(u){return u}
function marineURL(keys,model,extraVars,days,hours){const {lat,lon}=llFor(keys||ids());const vars=extraVars||"swell_wave_height,swell_wave_direction,swell_wave_period,wind_wave_height,wind_wave_direction,wind_wave_period,secondary_swell_wave_height,secondary_swell_wave_direction,secondary_swell_wave_period,wave_height,wave_period,wave_direction,sea_surface_temperature";let u=`https://marine-api.open-meteo.com/v1/marine?latitude=${lat}&longitude=${lon}&hourly=${vars}&timezone=${encodeURIComponent(MV)}&cell_selection=sea`;if(hours)u+=`&forecast_hours=${hours}`;else u+=`&forecast_days=${days||8}`;if(model)u+=`&models=${model}`;return wrapProxy(u)}
function currentURL(keys){const {lat,lon}=llFor(keys||ids());return wrapProxy(`https://marine-api.open-meteo.com/v1/marine?latitude=${lat}&longitude=${lon}&hourly=ocean_current_velocity,ocean_current_direction,sea_level_height_msl&forecast_days=8&timezone=${encodeURIComponent(MV)}&cell_selection=sea`)}
function windURL(keys){const {lat,lon}=llFor(keys||ids());return wrapProxy(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&hourly=wind_speed_10m,wind_direction_10m,wind_gusts_10m,cloud_cover,precipitation&forecast_days=16&timezone=${encodeURIComponent(MV)}&wind_speed_unit=kn`)}
function asList(x){return Array.isArray(x)?x:[x]}
function n(v,f=0){return typeof v==="number"&&isFinite(v)?v:f}
const CACHE_TTL=3*3600*1000;
function cacheGet(key){try{const raw=localStorage.getItem("kandu:"+key);if(!raw)return null;const o=JSON.parse(raw);if(!o||!o.at||Date.now()-o.at>CACHE_TTL)return null;return o.data}catch(e){return null}}
function cacheSet(key,data){try{localStorage.setItem("kandu:"+key,JSON.stringify({at:Date.now(),data}))}catch(e){}}
async function getJSON(url,tries=4){let last="network";for(let i=0;i<tries;i++){try{const ctl=new AbortController();const t=setTimeout(()=>ctl.abort(),25000);const r=await fetch(url,{signal:ctl.signal,mode:"cors",cache:"no-store"});clearTimeout(t);if(r.status===429){last="429 rate limit";await new Promise(x=>setTimeout(x,1500*(i+1)));continue}if(!r.ok)throw new Error("upstream "+r.status);return r.json()}catch(e){last=e.name==="AbortError"?"timeout":(e.message||String(e));if(i<tries-1)await new Promise(x=>setTimeout(x,700*(i+1)))}}throw new Error(last)}
async function getCached(key,url){try{const data=await getJSON(url);cacheSet(key,data);return {data,from:"live"}}catch(e){const hit=cacheGet(key);if(hit)return {data:hit,from:"cache",err:e.message};throw e}}
function parseCell(raw){const h=raw.hourly||{},t=h.time||[];return t.map((iso,i)=>({iso,ms:Date.parse(iso.includes("T")?iso+"+05:00":iso),Hs:n(h.swell_wave_height?.[i],n(h.wave_height?.[i])),dir:n(h.swell_wave_direction?.[i],n(h.wave_direction?.[i],180)),T:n(h.swell_wave_period?.[i],n(h.wave_period?.[i],8)),ww:n(h.wind_wave_height?.[i]),wwd:n(h.wind_wave_direction?.[i]),wwp:n(h.wind_wave_period?.[i],6),s2:n(h.secondary_swell_wave_height?.[i]),s2d:n(h.secondary_swell_wave_direction?.[i]),s2t:n(h.secondary_swell_wave_period?.[i]),s3:n(h.tertiary_swell_wave_height?.[i]),s3d:n(h.tertiary_swell_wave_direction?.[i]),s3t:n(h.tertiary_swell_wave_period?.[i]),sea:n(h.wave_height?.[i]),sst:h.sea_surface_temperature?.[i]??null}))}
function parseCur(raw){const h=raw.hourly||{},sl=(h.sea_level_height_msl||[]).filter(v=>typeof v==="number"),mean=sl.length?sl.reduce((a,b)=>a+b,0)/sl.length:0;return (h.time||[]).map((iso,i)=>{const kmh=n(h.ocean_current_velocity?.[i]);return {iso,ms:Date.parse(iso+"+05:00"),kn:Math.round(kmhToKn(kmh)*100)/100,dir:n(h.ocean_current_direction?.[i]),sl:n(h.sea_level_height_msl?.[i]),slAn:Math.round((n(h.sea_level_height_msl?.[i])-mean)*100)/100}})}
function windParse(raw){const h=raw.hourly||{};return (h.time||[]).map((iso,i)=>({iso,kn:n(h.wind_speed_10m?.[i]),dir:n(h.wind_direction_10m?.[i]),gust:n(h.wind_gusts_10m?.[i]),cloud:n(h.cloud_cover?.[i]),rain:n(h.precipitation?.[i])}))}
function idxNow(arr){const now=Date.now();let b=0;for(let i=0;i<arr.length;i++){if(arr[i].ms<=now)b=i;else break}return b}
function nearest(arr,ms){if(!arr||!arr.length)return null;let b=0,d=Infinity;for(let i=0;i<arr.length;i++){const x=Math.abs(arr[i].ms-ms);if(x<d){d=x;b=i}}return d<3.6e6*3?arr[b]:null}
function wrapHb(spot,Hs,ckn,crel,T){let w=1+(spot.wrap-1)*Math.max(0.35,Math.min(1.25,((T||8)-6.5)/8));if(ckn>=0.3&&crel==="oppose")w*=1+Math.min(0.18,ckn*0.08);if(ckn>=0.3&&crel==="follow")w*=1-Math.min(0.14,ckn*0.06);return Math.round(Hs*w*10)/10}
function hourOf(spot,cell,wi,i){const p=cell[i];if(!p)return null;const w=wi?.[i]||nearest(wi,p.ms),c=nearest(state.cur[spot.fk],p.ms);const wkn=w?n(w.kn,p.ww*8):Math.sqrt(Math.max(p.ww,0)/0.0246)*1.94384;const wdir=w?n(w.dir,p.wwd):p.wwd;const thHarm=tideH(p.ms,spot.lat),slAn=c?c.slAn:0,th=Math.round((thHarm+slAn*0.35)*100)/100,tb=band(th),ckn=c?c.kn:0,cdir=c?c.dir:0,crel=c?currentRel(p.dir,cdir):"slack";const r=rate(spot,{h:p.Hs,dir:p.dir,T:p.T,wkn,wdir,tb,hour:hourMvt(p.ms),ckn,crel,ww:p.ww});const Hb=wrapHb(spot,p.Hs,ckn,crel,p.T),fun=Math.max(spot.min,0.9),g=nearest(state.gfs[spot.fk],p.ms),e=nearest(state.ecm[spot.fk],p.ms);return {...p,wkn,wdir,th,tb,thHarm,slAn,Hb,ckn,cdir,crel,wait:waitMin(Hb,fun,p.T),kw:power(p.Hs,p.T),...r,src:sourceOf(p.dir,p.T),cloud:w?w.cloud:null,rain:w?w.rain:0,gHs:g?g.Hs:null,eHs:e?e.sea||e.Hs:null,s3:g?g.s3:p.s3,s3t:g?g.s3t:p.s3t,s3d:g?g.s3d:p.s3d}}
function scoreSpot(spot){const cell=state.cells[spot.fk];if(!cell)return null;const w=state.wind[spot.fk]||[],i=idxNow(cell),now=hourOf(spot,cell,w,i),next=cell.slice(i,Math.min(cell.length,i+48)).map((_,k)=>hourOf(spot,cell,w,i+k)).filter(Boolean);let best=now;for(const h of next)if(h.score>best.score)best=h;const sessions=[];let k=0;while(k<next.length){if(next[k].score<5.2){k++;continue}let j=k,b=next[k];while(j<next.length&&next[j].score>=5.2){if(next[j].score>b.score)b=next[j];j++}if(j-k>=2)sessions.push({start:next[k].iso,end:next[j-1].iso,hrs:j-k,score:b.score,label:b.label,flow:b.flow});k=Math.max(j,k+1)}const spreadParts=[];if(now.gHs!=null)spreadParts.push(Math.abs(now.gHs-now.Hs));if(now.eHs!=null)spreadParts.push(Math.abs(now.eHs-now.sea));const spread=spreadParts.length?Math.max(...spreadParts):null;const cons=next.length?next.filter(h=>h.score>=5.2).length/next.length:0;const conf=Math.max(0.28,Math.min(0.96,0.86-(spread??0)*0.32-(now.T<8?0.14:0)+(now.T>=13?0.06:0)+cons*0.08-(now.ckn>1.6?0.08:0)));return {spot,now,best,sessions,next,conf,spread,cons}}
function ranked(){return SPOTS.map(scoreSpot).filter(Boolean).sort((a,b)=>b.now.score-a.now.score)}
function specEnergy(h){const bins=BANDS.map(()=>0);const add=(H,T)=>{if(!H||H<0.05||!T)return;const e=H*H*Math.max(T,4);for(let i=0;i<BANDS.length;i++){if(T>=BANDS[i][0]&&T<BANDS[i][1]){bins[i]+=e;return}}bins[bins.length-1]+=e};add(h.Hs,h.T);add(h.s2,h.s2t);add(h.s3,h.s3t);add(h.ww,h.wwp);const mx=Math.max(0.001,...bins);return bins.map(v=>v/mx)}
