window.LM_SPOTS = [
  { id:"chickens", name:"Chickens", atoll:"North Male", island:"Viligilimathidhahuraa", lat:4.3750, lon:73.6632, side:"L", swell:135, wind:20, difficulty:"Advanced", desc:"Long left across the channel from Thulusdhoo." },
  { id:"cokes", name:"Cokes", atoll:"North Male", island:"Thulusdhoo", lat:4.3722, lon:73.6524, side:"R", swell:160, wind:10, difficulty:"Advanced", desc:"Hollow right off the old Coke plant." },
  { id:"tombstones", name:"Tombstones", atoll:"North Male", island:"Thulusdhoo reef", lat:4.3600, lon:73.6400, side:"R", swell:150, wind:20, difficulty:"Expert", desc:"Heavy east-reef right." },
  { id:"ninjas", name:"Ninjas", atoll:"North Male", island:"Huraa reef", lat:4.3336, lon:73.6080, side:"L", swell:140, wind:20, difficulty:"Advanced", desc:"Punchy left on the Huraa reef line." },
  { id:"lohis", name:"Lohis", atoll:"North Male", island:"Lohifushi / Hudhuranfushi", lat:4.3100, lon:73.6050, side:"L", swell:140, wind:20, difficulty:"Intermediate", desc:"Long left in front of Hudhuranfushi." },
  { id:"pasta-point", name:"Pasta Point", atoll:"North Male", island:"Kanuhuraa / Dhonveli", lat:4.3183, lon:73.5917, side:"L", swell:150, wind:40, difficulty:"Intermediate", desc:"Cinnamon Dhonveli exclusive left." },
  { id:"sultans", name:"Sultans", atoll:"North Male", island:"Thanburudhoo", lat:4.3160, lon:73.5885, side:"R", swell:155, wind:250, difficulty:"Intermediate", desc:"House right off Thanburudhoo." },
  { id:"honkeys", name:"Honkeys", atoll:"North Male", island:"Thanburudhoo", lat:4.3148, lon:73.5805, side:"L", swell:160, wind:50, difficulty:"Intermediate", desc:"Left on the other side of Thanburudhoo." },
  { id:"jailbreaks", name:"Jailbreaks", atoll:"North Male", island:"Himmafushi", lat:4.3080, lon:73.5711, side:"R", swell:150, wind:250, difficulty:"Expert", desc:"Fast right off the old prison island." },
  { id:"raalhugandu", name:"Raalhugandu", atoll:"North Male", island:"Male", lat:4.1748, lon:73.5192, side:"R", swell:140, wind:270, difficulty:"Beginner", desc:"Urban reef off Artificial Beach." },
  { id:"gurus", name:"Gurus", atoll:"South Male", island:"Guraidhoo north reef", lat:3.9120, lon:73.4750, side:"L", swell:150, wind:40, difficulty:"Advanced", desc:"Long left on bigger S-SE swell." },
  { id:"foxys", name:"Foxys", atoll:"South Male", island:"Guraidhoo", lat:3.9050, lon:73.4700, side:"R", swell:160, wind:250, difficulty:"Intermediate", desc:"Consistent right in the Guraidhoo channel." },
  { id:"kandooma-right", name:"Kandooma Right", atoll:"South Male", island:"Kandooma / Guraidhoo", lat:3.9030, lon:73.4730, side:"R", swell:160, wind:260, difficulty:"Advanced", desc:"Barreling right over shallow reef." },
  { id:"quarters", name:"Quarters", atoll:"South Male", island:"Guraidhoo", lat:3.9008, lon:73.4681, side:"R", swell:155, wind:250, difficulty:"Intermediate", desc:"Short punchy right." },
  { id:"tucky-joes", name:"Tucky Joes", atoll:"South Male", island:"Guraidhoo", lat:3.8980, lon:73.4650, side:"L", swell:150, wind:40, difficulty:"Intermediate", desc:"Left walls in the same reef complex." },
  { id:"lohis-left", name:"Lohi's Left", atoll:"South Male", island:"Guraidhoo", lat:3.8970, lon:73.4620, side:"L", swell:145, wind:30, difficulty:"Beginner", desc:"Mellow South Male left." },
  { id:"native", name:"Native", atoll:"South Male", island:"Maafushi reef", lat:3.9410, lon:73.4897, side:"L", swell:150, wind:40, difficulty:"Intermediate", desc:"Consistent left off Maafushi." },
  { id:"kudarah-thila", name:"Kudarah Thila", atoll:"Ari", island:"Kudarah", lat:3.5470, lon:72.8940, side:"R", swell:180, wind:40, difficulty:"Advanced", desc:"Outer-reef right, South Ari." },
  { id:"boilers", name:"Boilers", atoll:"Ari", island:"South Ari outer reef", lat:3.5300, lon:72.8800, side:"L", swell:200, wind:50, difficulty:"Expert", desc:"Heavy left over shallow reef." },
  { id:"twin-peaks", name:"Twin Peaks", atoll:"Ari", island:"Dhigurah reef", lat:3.5100, lon:72.9000, side:"Both", swell:190, wind:40, difficulty:"Intermediate", desc:"Two peaks, multiple takeoffs." },
  { id:"donkeys", name:"Donkeys", atoll:"Ari", island:"Dhidhdhoofinolhu", lat:3.4900, lon:72.8780, side:"R", swell:180, wind:40, difficulty:"Beginner", desc:"Playful South Ari right." },
  { id:"riptides", name:"Riptides", atoll:"Ari", island:"South Ari west reef", lat:3.5200, lon:72.8500, side:"R", swell:200, wind:50, difficulty:"Intermediate", desc:"Long right point on S-SW swell." },
  { id:"hanifaru-rights", name:"Hanifaru Rights", atoll:"Baa", island:"Hanifaru", lat:5.1720, lon:73.1430, side:"R", swell:180, wind:40, difficulty:"Intermediate", desc:"Right near the manta bay." },
  { id:"dharavandhoo-left", name:"Dharavandhoo Left", atoll:"Baa", island:"Dharavandhoo", lat:5.1573, lon:73.1310, side:"L", swell:170, wind:50, difficulty:"Beginner", desc:"Mellow left in the biosphere reserve." },
  { id:"veyvah-left", name:"Veyvah Left", atoll:"Meemu", island:"Veyvah", lat:2.9560, lon:73.6030, side:"L", swell:150, wind:40, difficulty:"Advanced", desc:"Punchy left, short barrels." },
  { id:"muli-right", name:"Muli Right", atoll:"Meemu", island:"Muli", lat:2.9221, lon:73.5815, side:"R", swell:160, wind:260, difficulty:"Intermediate", desc:"Long right point on S-SW swell." },
  { id:"hocus-pocus", name:"Hocus Pocus", atoll:"Meemu", island:"Muli reef", lat:2.9180, lon:73.5880, side:"R", swell:155, wind:260, difficulty:"Advanced", desc:"Fast right off Muli." },
  { id:"maliks", name:"Malik's", atoll:"Meemu", island:"Maalifushi north", lat:2.9000, lon:73.4800, side:"L", swell:160, wind:40, difficulty:"Intermediate", desc:"Uncrowded left near the Farms complex." },
  { id:"bowling-alley", name:"Bowling Alley", atoll:"Meemu", island:"Maalifushi", lat:2.8960, lon:73.4750, side:"R", swell:170, wind:260, difficulty:"Advanced", desc:"Powerful right." },
  { id:"inside-mikados", name:"Inside Mikados", atoll:"Meemu", island:"Maalifushi", lat:2.8920, lon:73.4700, side:"R", swell:165, wind:260, difficulty:"Intermediate", desc:"Inside right in the Farms area." },
  { id:"farms", name:"Farms", atoll:"Meemu", island:"COMO Maalifushi", lat:2.8900, lon:73.4680, side:"Both", swell:170, wind:40, difficulty:"Intermediate", desc:"Reef complex off Maalifushi." },
  { id:"two-ways", name:"Two Ways", atoll:"Dhaalu", island:"Kudahuvadhoo reef", lat:2.6900, lon:72.9200, side:"Both", swell:180, wind:40, difficulty:"Intermediate", desc:"Bi-directional peak." },
  { id:"kasabu", name:"Kasabu", atoll:"Dhaalu", island:"Kudahuvadhoo", lat:2.6712, lon:72.8938, side:"R", swell:180, wind:40, difficulty:"Intermediate", desc:"Playful right near the atoll capital." },
  { id:"vodi", name:"Vodi", atoll:"Dhaalu", island:"Kudahuvadhoo east", lat:2.6800, lon:72.9100, side:"L", swell:160, wind:40, difficulty:"Advanced", desc:"Fast left, uncrowded." },
  { id:"vilufushi-left", name:"Vilufushi Left", atoll:"Thaa", island:"Vilufushi", lat:2.5030, lon:73.3080, side:"L", swell:150, wind:40, difficulty:"Intermediate", desc:"Long peeling left." },
  { id:"madifushi-right", name:"Madifushi Right", atoll:"Thaa", island:"Madifushi", lat:2.3550, lon:73.2650, side:"R", swell:170, wind:260, difficulty:"Beginner", desc:"Consistent right on smaller days." },
  { id:"isdhoo", name:"Isdhoo", atoll:"Laamu", island:"Isdhoo", lat:2.1180, lon:73.5690, side:"R", swell:140, wind:260, difficulty:"Intermediate", desc:"Long scenic right, north Laamu." },
  { id:"hithadhoo-rights", name:"Hithadhoo Rights", atoll:"Laamu", island:"Hithadhoo Laamu", lat:1.8000, lon:73.4300, side:"R", swell:150, wind:260, difficulty:"Intermediate", desc:"Multiple right peaks." },
  { id:"yin-yang-right", name:"Yin Yang Right", atoll:"Laamu", island:"Olhuveli / Six Senses", lat:1.8130, lon:73.4380, side:"R", swell:155, wind:260, difficulty:"Advanced", desc:"Bowling right off Six Senses Laamu." },
  { id:"yin-yang-left", name:"Yin Yang Left", atoll:"Laamu", island:"Olhuveli / Six Senses", lat:1.8115, lon:73.4350, side:"L", swell:150, wind:40, difficulty:"Intermediate", desc:"The left sibling." },
  { id:"machines", name:"Machines", atoll:"Laamu", island:"Laamu east reef", lat:1.7980, lon:73.4180, side:"L", swell:150, wind:40, difficulty:"Advanced", desc:"Long mechanical left." },
  { id:"refugees-lefts", name:"Refugees Lefts", atoll:"Laamu", island:"Laamu east reef", lat:1.8000, lon:73.4100, side:"L", swell:150, wind:40, difficulty:"Intermediate", desc:"Fun lefts next door to Machines." },
  { id:"antiques", name:"Antiques", atoll:"Huvadhoo", island:"Gaafu Alifu north reef", lat:0.6500, lon:73.2000, side:"R", swell:180, wind:20, difficulty:"Advanced", desc:"Remote northern Huvadhoo right." },
  { id:"tiger-stripes", name:"Tiger Stripes", atoll:"Huvadhoo", island:"Gaafu Alifu west", lat:0.5500, lon:73.1000, side:"L", swell:200, wind:40, difficulty:"Intermediate", desc:"Long left with tiger-stripe sand." },
  { id:"beacons", name:"Beacons", atoll:"Huvadhoo", island:"Fiyoaree pass", lat:0.2300, lon:73.1400, side:"R", swell:200, wind:20, difficulty:"Expert", desc:"Barracuda Point. Gnarliest right in the south." },
  { id:"castaways", name:"Castaways", atoll:"Huvadhoo", island:"Farukolhuhuttaa", lat:0.2250, lon:73.2000, side:"R", swell:200, wind:10, difficulty:"Intermediate", desc:"Right about 7 km from Beacons." },
  { id:"blue-bowls", name:"Blue Bowls", atoll:"Huvadhoo", island:"Vaadhoo", lat:0.2321, lon:73.2871, side:"R", swell:200, wind:350, difficulty:"Beginner", desc:"Flexible right in the Vaadhoo pass." },
  { id:"love-charms", name:"Love Charms", atoll:"Huvadhoo", island:"Vaadhoo reef", lat:0.2200, lon:73.2700, side:"R", swell:190, wind:10, difficulty:"Intermediate", desc:"Playful southern Huvadhoo right." },
  { id:"five-islands", name:"Five Islands", atoll:"Huvadhoo", island:"Boduhuttaa", lat:0.2700, lon:73.2300, side:"R", swell:190, wind:300, difficulty:"Advanced", desc:"Gani Point. Hollow inside." },
  { id:"madihera", name:"Madihera", atoll:"Huvadhoo", island:"Gaafu Dhaalu south", lat:0.2100, lon:73.2500, side:"L", swell:180, wind:40, difficulty:"Intermediate", desc:"Southern Huvadhoo left." },
  { id:"kottey", name:"Kottey", atoll:"Huvadhoo", island:"Gaafu Dhaalu south", lat:0.2000, lon:73.2550, side:"R", swell:180, wind:300, difficulty:"Intermediate", desc:"Right in the deep south of Huvadhoo." },
  { id:"equator-point", name:"Equator Point", atoll:"Addu", island:"Gan channel", lat:-0.6400, lon:73.1500, side:"R", swell:180, wind:40, difficulty:"Intermediate", desc:"Named break in the Gan approaches." },
  { id:"addu-rights", name:"Addu Rights", atoll:"Addu", island:"Villingili Addu", lat:-0.6280, lon:73.0880, side:"R", swell:190, wind:40, difficulty:"Intermediate", desc:"West Addu right." },
  { id:"shangri-la", name:"Shangri-la", atoll:"Addu", island:"Villingili / Shangri-La", lat:-0.6230, lon:73.0900, side:"R", swell:180, wind:40, difficulty:"Beginner", desc:"Mellow resort wave off Villingili." },
  { id:"gan-island-rights", name:"Gan Island Rights", atoll:"Addu", island:"Gan", lat:-0.6940, lon:73.1560, side:"R", swell:170, wind:40, difficulty:"Beginner", desc:"Accessible right off the airport island." },
  { id:"approach-lights", name:"Approach Lights", atoll:"Addu", island:"Gan runway", lat:-0.6980, lon:73.1520, side:"R", swell:170, wind:40, difficulty:"Intermediate", desc:"Right under the Gan approach lights." }
];
window.LM_WORLD = [
  { id:"pipeline", name:"Pipeline", atoll:"World", island:"Oahu", lat:21.665, lon:-158.054, side:"L", swell:310, wind:70, difficulty:"Expert", desc:"Deadly barrels.", world:true },
  { id:"teahupoo", name:"Teahupo'o", atoll:"World", island:"Tahiti", lat:-17.841, lon:-149.267, side:"L", swell:180, wind:20, difficulty:"Expert", desc:"Heavy left slab.", world:true },
  { id:"jbay", name:"Jeffreys Bay", atoll:"World", island:"South Africa", lat:-34.05, lon:24.92, side:"R", swell:220, wind:270, difficulty:"Advanced", desc:"Endless right point.", world:true },
  { id:"uluwatu", name:"Uluwatu", atoll:"World", island:"Bali", lat:-8.813, lon:115.087, side:"L", swell:210, wind:90, difficulty:"Advanced", desc:"Cliff lefts.", world:true },
  { id:"superbank", name:"Superbank", atoll:"World", island:"Gold Coast", lat:-28.16, lon:153.53, side:"R", swell:90, wind:250, difficulty:"Advanced", desc:"Man-made rights.", world:true },
  { id:"pavones", name:"Pavones", atoll:"World", island:"Costa Rica", lat:8.43, lon:-83.11, side:"L", swell:220, wind:40, difficulty:"Intermediate", desc:"Long left.", world:true },
  { id:"peniche", name:"Peniche", atoll:"World", island:"Portugal", lat:39.36, lon:-9.38, side:"R", swell:280, wind:40, difficulty:"Advanced", desc:"Supertubos.", world:true },
  { id:"burleigh", name:"Burleigh Heads", atoll:"World", island:"Gold Coast", lat:-28.09, lon:153.46, side:"R", swell:90, wind:250, difficulty:"Intermediate", desc:"Point perfection.", world:true },
  { id:"noosa", name:"Noosa", atoll:"World", island:"Queensland", lat:-26.39, lon:153.09, side:"R", swell:90, wind:250, difficulty:"Beginner", desc:"Long peeling rights.", world:true },
  { id:"escondido", name:"Puerto Escondido", atoll:"World", island:"Mexico", lat:15.86, lon:-97.07, side:"Both", swell:210, wind:20, difficulty:"Expert", desc:"Mexican Pipeline.", world:true },
  { id:"hossegor", name:"Hossegor", atoll:"World", island:"France", lat:43.67, lon:-1.44, side:"Both", swell:280, wind:90, difficulty:"Advanced", desc:"Beachbreak barrels.", world:true },
  { id:"trestles", name:"Trestles", atoll:"World", island:"California", lat:33.38, lon:-117.60, side:"Both", swell:220, wind:40, difficulty:"Intermediate", desc:"High-performance peaks.", world:true },
  { id:"raglan", name:"Raglan", atoll:"World", island:"New Zealand", lat:-37.80, lon:174.85, side:"L", swell:230, wind:90, difficulty:"Intermediate", desc:"Long left points.", world:true },
  { id:"cloudbreak", name:"Cloudbreak", atoll:"World", island:"Fiji", lat:-17.65, lon:177.25, side:"L", swell:180, wind:90, difficulty:"Expert", desc:"World-class reef left.", world:true },
  { id:"mentawai", name:"Mentawai", atoll:"World", island:"Indonesia", lat:-2.00, lon:99.50, side:"Both", swell:210, wind:90, difficulty:"Advanced", desc:"Jungle-reef perfection.", world:true }
];
window.LM_ATOLLS = ["North Male","South Male","Ari","Baa","Meemu","Dhaalu","Thaa","Laamu","Huvadhoo","Addu"];
window.LM_DEFAULT = "sultans";
